# Generated by Django 5.1.3 on 2024-11-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloques_Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Seccion', models.CharField(choices=[('0', 'Home'), ('1', 'Galeria'), ('2', 'Noticias'), ('3', 'Recursos'), ('4', 'Reservas')], max_length=2, verbose_name='Seccion')),
            ],
        ),
    ]
