# Generated by Django 5.1.3 on 2024-11-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_bloques_contenido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloques_Contenido',
            new_name='Content_Blocks',
        ),
        migrations.DeleteModel(
            name='Secciones',
        ),
        migrations.RenameField(
            model_name='content_blocks',
            old_name='Nombre',
            new_name='Name',
        ),
    ]
