# Generated by Django 5.1.3 on 2024-11-06 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_bloques_contenido_content_blocks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content_blocks',
            old_name='Seccion',
            new_name='Section',
        ),
        migrations.AddField(
            model_name='content_blocks',
            name='Body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
