# Generated by Django 5.1.3 on 2024-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerysubsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos_bioDiversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='img')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
            ],
        ),
    ]
