# Generated by Django 5.1.3 on 2024-11-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photos_biodiversity_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos_biodiversity',
            name='photo',
            field=models.ImageField(upload_to='static/Photos', verbose_name='img'),
        ),
    ]
