# Generated by Django 5.1.3 on 2024-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_delete_photos_biodiversity'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='Section_section',
            field=models.CharField(blank=True, choices=[('0', 'general'), ('1', 'biodiversidad'), ('2', 'actividades'), ('4', 'amenazas')], max_length=2, verbose_name='Seccion'),
        ),
    ]
