# Generated by Django 5.1.3 on 2024-11-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photos_section_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='Section_section',
            new_name='Section',
        ),
    ]
