# Generated by Django 5.1.3 on 2024-11-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_danger'),
    ]

    operations = [
        migrations.CreateModel(
            name='seccionFauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('photo', models.ImageField(upload_to='static/faunaPhotos', verbose_name='img')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='Section',
            field=models.CharField(blank=True, choices=[('0', 'general'), ('1', 'biodiversidad'), ('2', 'actividades'), ('3', 'amenazas'), ('4', 'flora')], max_length=2, verbose_name='Seccion'),
        ),
    ]
