# Generated by Django 5.1.3 on 2024-11-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_seccionfauna_alter_photos_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seccionFauna',
            new_name='SectionFauna',
        ),
    ]
